name: App Build and Push
 
on:
  push:

env:
  TERRAFORM_PATH: ${{ vars.TERRAFORM_PATH }}
  TERRAFORM_BACKEND_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_BACKEND_SUBSCRIPTION_ID }}
  TERRAFORM_BACKEND_RESOURCE_GROUP: ${{ secrets.TERRAFORM_BACKEND_RESOURCE_GROUP }}
  TERRAFORM_BACKEND_STORAGE_ACCOUNT: ${{ secrets.TERRAFORM_BACKEND_STORAGE_ACCOUNT }}
  TERRAFORM_BACKEND_CONTAINER: ${{ secrets.TERRAFORM_BACKEND_CONTAINER }}
  TERRAFORM_BACKEND_STATE_FILE: ${{ secrets.TERRAFORM_BACKEND_STATE_FILE }}
  APP_PATH: ${{ vars.APP_PATH }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

jobs:
  app-build-and-push:
    name: App Build and Push
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@main
      id: setup
    
    - name: Terraform Init
      id: terra-init
      run: |
        make terra-init

    - name: App Build
      id: build
      run: |
        make app-build
      env: 
        IMAGE_TAG: ${{ github.sha }}