name: App Build
 
on:
  push:
    paths:
    - src
    - scripts/app.sh
    - Makefile

env:
  APP_PATH: ${{ vars.APP_PATH }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
  TF_VAR_ACR_NAME: ${{ secrets.TF_VAR_ACR_NAME }}
  TF_VAR_IMAGE_NAME: ${{ secrets.TF_VAR_IMAGE_NAME }}

jobs:
  app-build:
    name: App Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@main
      id: setup
    
    - name: App Build
      id: build
      run: |
        make app-build
      env: 
        IMAGE_TAG: ${{ github.sha }}